fifa_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"  # Docker: postgres - CI: localhost
      port: 5432
      dbname: fifa_dw
      user: root
      password: root
      schema: public
      threads: 1